id: IE46E4458
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:07:06+00:00'
last_modified: '2022-06-08T07:58:33.888318+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5303
  title: མཛེས་རྩལ་དཔེ་རིས་སྦྲང་མའི་ཤོག་རླབས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6602':
      image_group_id: I3CN5305
      title: ''
      total_pages: 124
      order: 1
      base_file: 6602.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
